name: pasteque_match
description: Mobile app to help parents find a name for their baby
publish_to: 'none'
version: 1.4.0+11

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Framework Tools
  fetcher: ^4.3.1

  # Widgets / UI
  flash: ^3.1.1
  font_awesome_flutter: ^10.12.0
  appinio_swiper: 2.0.3
  fl_chart: ^1.1.1
  animated_list_plus: ^0.5.2
  confetti: ^0.8.0
  pretty_qr_code: ^3.5.0

  # Network
  connectivity_plus: ^6.1.5
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  firebase_messaging: ^16.1.1
  firebase_cloud_messaging_flutter: ^1.0.6

  # Data management
  cloud_firestore: ^6.1.2
  shared_preferences: ^2.5.4
  fast_csv: ^0.2.11

  # Platform tools
  mobile_scanner: ^7.1.4

  # Internationalization
  intl: any  # Version pinned by Flutter SDK
  diacritic: ^0.1.6

dev_dependencies:
  # Code style
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.10.5
  json_serializable: ^6.11.4

  # Scripting
  spreadsheet_decoder: ^2.2.0
  csv : ^5.0.1

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Passions Conflict
      fonts:
        - asset: assets/fonts/PassionsConflict-Regular.ttf
          weight: 400
    - family: Merienda
      fonts:
        - asset: assets/fonts/Merienda-Regular.ttf
          weight: 400
